[package]
name = "gas-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
serde = "1.0.217"

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_postgres"]

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"]
